### PR TITLE
exotica_python: Add PlanningSceneUtils

### PR DESCRIPTION
**Pull request by wxmerkt**
- Adds convenience functions to easily create collision objects that can be added to a ``moveit_msgs::PlanningSceneWorld``
- Supports building mesh objects from files (currently requires absolute paths for mesh files)

Setup with a few lines of Python:
image

### CODE REVIEW

**Comment by wxmerkt** [comment]
Now also includes a wrapper for ``setCollisionScene`` which accepts ``moveit_msgs::PlanningScene`` which allow setting entire planning scenes as well as specifying colour:

image

**Comment by wxmerkt** [comment]
Now also includes a debug variant of ``getClosestDistance(debug=True)`` which outputs the collision pairs as ROS warnings, e.g:

```
[ WARN] [1504721578.173168314]: Number of Environment Contacts:1
[ WARN] [1504721578.173202914]: Contact between: shelf and torso
```
for:
image

**Comment by VladimirIvan** [comment]
I have added loading from a scene file. I had this stashed in a local branch.
I have also added relative paths to the mesh loading.
Good to go if you are happy with the changes I made.

**Comment by wxmerkt** [comment]
Thank you, these are really useful additions :-)

**Pull request merged**
